### ISSUE TITLE
Adjust balance at start, crash

### ISSUE THREAD

**Issue by jpsember** [jpsember/bk#61]
```
*** account    1000 : Asset budget balance was incorrect:
    $910.28 , should be:
    $300.00
Exception in thread "main" java.lang.NullPointerException: adjustBalance, no such account:    1020
	at js.base.Tools.checkNotNull(Tools.java:697)
	at bk.Storage.adjustBalance(Storage.java:374)
	at bk.Storage.applyTransactionToAccountBalances(Storage.java:365)
	at bk.Storage.addOrReplace(Storage.java:300)
	at bk.RuleManager.applyRules(RuleManager.java:66)
	at bk.RuleManager.applyRulesToAllTransactions(RuleManager.java:43)
	at bk.BkOper.perform(BkOper.java:58)
	at js.app.App.auxRunOper(App.java:155)
	at js.app.App.runApplication(App.java:148)
	at js.app.App.startApplication(App.java:101)
	at bk.Bk.main(Bk.java:12)
bk] 
```

**Comment by jpsember** [comment]
This is because the rules don't know about edited account numbers
